In [3]:
import requests
import json
import numpy as np
import pandas as pd
import time

with open('../Data/api_key.json') as fi:
    credentials = json.load(fi)
    
api_key = credentials['api_key']

In [21]:
header={
    "Accept":"application/json", 
    "x-api-key":api_key
}


a=requests.get("https://api.setlist.fm/rest/1.0/artist/af953ba2-283b-41ef-93bc-b4cfc5feeebc", headers=header)
print(a)
a_dict = a.json()

<Response [200]>

In [22]:
for key, value in a_dict.items():
    print(f"\nKey: {key}")
    print(f"Value: {value}\n")

Key: mbid
Value: af953ba2-283b-41ef-93bc-b4cfc5feeebc


Key: name
Value: Darlene Love


Key: sortName
Value: Love, Darlene


Key: disambiguation
Value:


Key: url
Value: https://www.setlist.fm/setlists/darlene-love-bd69d4e.html

In [23]:
# data = [{'name': 'vikash', 'age': 27}, {'name': 'Satyam', 'age': 14}]
# df = pd.DataFrame.from_dict(data, orient='columns')

a_dict.keys()

dict_keys(['mbid', 'name', 'sortName', 'disambiguation', 'url'])

In [24]:
a_dict.values()

dict_values(['af953ba2-283b-41ef-93bc-b4cfc5feeebc', 'Darlene Love', 'Love, Darlene', '', 'https://www.setlist.fm/setlists/darlene-love-bd69d4e.html'])

In [25]:
a_dict.items()

dict_items([('mbid', 'af953ba2-283b-41ef-93bc-b4cfc5feeebc'), ('name', 'Darlene Love'), ('sortName', 'Love, Darlene'), ('disambiguation', ''), ('url', 'https://www.setlist.fm/setlists/darlene-love-bd69d4e.html')])

In [26]:
a_dict['name']

'Darlene Love'

In [27]:

a_dict

{'mbid': 'af953ba2-283b-41ef-93bc-b4cfc5feeebc',
 'name': 'Darlene Love',
 'sortName': 'Love, Darlene',
 'disambiguation': '',
 'url': 'https://www.setlist.fm/setlists/darlene-love-bd69d4e.html'}

In [28]:
# loop to print all keys

for x in a_dict:
    print(x)

mbid
name
sortName
disambiguation
url

In [29]:
# loop to print all values

for x in a_dict:
    print(a_dict[x])

af953ba2-283b-41ef-93bc-b4cfc5feeebc
Darlene Love
Love, Darlene

https://www.setlist.fm/setlists/darlene-love-bd69d4e.html

In [31]:
for x in a_dict.values():
    print(x)

af953ba2-283b-41ef-93bc-b4cfc5feeebc
Darlene Love
Love, Darlene

https://www.setlist.fm/setlists/darlene-love-bd69d4e.html

In [32]:
for x in a_dict.keys():
    print(x)

mbid
name
sortName
disambiguation
url

In [33]:
for x, y in a_dict.items():
    print(x,y)

mbid af953ba2-283b-41ef-93bc-b4cfc5feeebc
name Darlene Love
sortName Love, Darlene
disambiguation
url https://www.setlist.fm/setlists/darlene-love-bd69d4e.html

In [40]:
# new = pd.DataFrame.from_dict(data)

# df = pd.DataFrame.from_dict(a_dict,index=[0])

a_df = pd.DataFrame(a_dict, index=[0])
a_df

,mbid,name,sortName,disambiguation,url
0,af953ba2-283b-41ef-93bc-b4cfc5feeebc,Darlene Love,"Love, Darlene",,https://www.setlist.fm/setlists/darlene-love-b...

In [ ]:
#  print("Type:", type(data))

print("Type:", type(a_dict)

In [ ]:


# b_df=pd.DataFrame(b.json())
# b_df.head()

# b_setlist_df = b_df['setlist'].apply(pd.Series)
# b_setlist_df.head()

In [ ]:
g_test = g.json()
ids = []
versionid = []
eventdate = []
lastupdated = []
artist = []
mbid = []
venue = []
song = []
for x in g_test['setlist']:
        song.append(y['name'])
        ids.append(x['id'])
        versionid.append(x['versionId'])
        eventdate.append(x['eventDate'])
        lastupdated.append(x['lastUpdated'])
        artist.append(x['artist']['name'])
        mbid.append(x['artist']['mbid'])
        venue.append(x['venue']['name'])
g_df_test = pd.DataFrame({'id': ids, 'versionid': versionid, 'eventdate': eventdate, 'lastupdated': lastupdated, 'artist': artist,'mbid':mbid, 'venue': venue, 'song': song})
g_df_test

In [42]:
header={
    "Accept":"application/json", 
    "x-api-key":api_key
}


d=requests.get("https://api.setlist.fm/rest/1.0/search/artists?artistName=The%20Beatles&p=1&sort=sortName", headers=header)
d_df=pd.DataFrame(d.json())
d_artist_df = d_df['artist'].apply(pd.Series)
d_artist_df.head()

,mbid,name,sortName,disambiguation,url
0,9725f5a1-3d65-488a-8a82-54c1483beb7c,The Anal Beatles,"Anal Beatles, The",,https://www.setlist.fm/setlists/the-anal-beatl...
1,ec996b5f-89c8-4dd6-8063-1bd8df438a00,The Backbeat Beatles,"Backbeat Beatles, The",,https://www.setlist.fm/setlists/the-backbeat-b...
2,898e211b-06ad-460b-85ee-cd6ac337ef79,The Beatles Connection,"Beatles Connection, The",Beatles Tribute Band,https://www.setlist.fm/setlists/the-beatles-co...
3,31f6812d-12ab-406f-a13d-ad54976e49c6,The Cavern Beatles,Beatles Cover Band,Beatles Cover Band,https://www.setlist.fm/setlists/the-cavern-bea...
4,f94d056f-68dc-4a99-b664-fa296a96240f,The Beatles First Five,"Beatles First Five, The",,https://www.setlist.fm/setlists/the-beatles-fi...

SEARCH SETLISTS using country code US

In [45]:
header={
    "Accept":"application/json", 
    "x-api-key":api_key
}


g=requests.get("https://api.setlist.fm/rest/1.0/search/setlists?countryCode=us&p=1", headers=header)
g_df=pd.DataFrame(g.json())

g_df

,type,itemsPerPage,page,total,setlist
0,setlists,20,1,2808972,"{'id': '53bf4f99', 'versionId': 'g43e2d3c7', '..."
1,setlists,20,1,2808972,"{'id': '4bbf4f9a', 'versionId': 'g5be2d3c0', '..."
2,setlists,20,1,2808972,"{'id': '43bf4f9b', 'versionId': 'g43e2d3c3', '..."
3,setlists,20,1,2808972,"{'id': '5bbf4fa4', 'versionId': 'g53e2d3cd', '..."
4,setlists,20,1,2808972,"{'id': '4bbf4fa6', 'versionId': 'g53e2d3c9', '..."
5,setlists,20,1,2808972,"{'id': '43bf4fab', 'versionId': 'g4be2d3e2', '..."
6,setlists,20,1,2808972,"{'id': '53bf4fb5', 'versionId': 'g53e2d3ed', '..."
7,setlists,20,1,2808972,"{'id': '4bbf4fb6', 'versionId': 'g43e2d3ef', '..."
8,setlists,20,1,2808972,"{'id': '53bf4fb1', 'versionId': 'g43e2d3eb', '..."
9,setlists,20,1,2808972,"{'id': '5bbf4fbc', 'versionId': 'g53e2d3f1', '..."
10,setlists,20,1,2808972,"{'id': '43bf4fbf', 'versionId': 'g5be2d3fc', '..."
11,setlists,20,1,2808972,"{'id': '43bf4fbb', 'versionId': 'g5be2d3f8', '..."
12,setlists,20,1,2808972,"{'id': '53bf4fc5', 'versionId': 'g4be2d3fa', '..."
13,setlists,20,1,2808972,"{'id': '5bbf4fc0', 'versionId': 'g53e2d305', '..."
14,setlists,20,1,2808972,"{'id': '5bbf4fcc', 'versionId': 'g53e2d301', '..."
15,setlists,20,1,2808972,"{'id': '4bbf4fce', 'versionId': 'g43e2d303', '..."
16,setlists,20,1,2808972,"{'id': '43bf4fcf', 'versionId': 'g5be2d30c', '..."
17,setlists,20,1,2808972,"{'id': '5bbf4fc8', 'versionId': 'g4be2d30e', '..."
18,setlists,20,1,2808972,"{'id': '53bf4fc9', 'versionId': 'g43e2d30f', '..."
19,setlists,20,1,2808972,"{'id': '4bbf4fca', 'versionId': 'g5be2d308', '..."

In [46]:
g_setlist_df = g_df['setlist'].apply(pd.Series)
g_setlist_df.head()

,id,versionId,eventDate,lastUpdated,artist,venue,tour,sets,url,info
0,53bf4f99,g43e2d3c7,10-12-2022,2022-12-08T00:17:59.000+0000,{'mbid': 'f6c6ff48-5198-47dc-a7c5-fd733dc379a2...,"{'id': '43d63b03', 'name': 'The Moore Theatre'...",{'name': 'Christmas In Hawai'i 2022'},{'set': []},https://www.setlist.fm/setlist/jake-shimabukur...,NaN
1,4bbf4f9a,g5be2d3c0,10-12-2022,2022-12-08T00:17:15.000+0000,{'mbid': '0330a83d-f61e-4989-adb3-afce3943c3ba...,"{'id': '1bd27580', 'name': 'Ritz Carlton', 'ci...",NaN,{'set': []},https://www.setlist.fm/setlist/38-special/2022...,NaN
2,43bf4f9b,g43e2d3c3,10-12-2022,2022-12-08T00:16:33.000+0000,{'mbid': '3ac482b8-1494-4071-a0e9-f192f9d2c2b0...,"{'id': '1bd61950', 'name': 'Pappy & Harriet's ...",{'name': 'Summer and Fall Tour 2022'},{'set': []},https://www.setlist.fm/setlist/built-to-spill/...,NaN
3,5bbf4fa4,g53e2d3cd,10-12-2022,2022-12-08T00:15:43.000+0000,{'mbid': '511562a6-c381-44df-9bc4-27be779716b8...,"{'id': '33d4b801', 'name': 'Yoshi's Oakland', ...",NaN,{'set': []},https://www.setlist.fm/setlist/tony-toni-tone/...,Late show
4,4bbf4fa6,g53e2d3c9,10-12-2022,2022-12-08T00:15:17.000+0000,{'mbid': '511562a6-c381-44df-9bc4-27be779716b8...,"{'id': '33d4b801', 'name': 'Yoshi's Oakland', ...",NaN,{'set': []},https://www.setlist.fm/setlist/tony-toni-tone/...,Early show

In [50]:
g_artist_df = g_setlist_df['artist'].apply(pd.Series)
g_artist_df

,mbid,name,sortName,disambiguation,url
0,f6c6ff48-5198-47dc-a7c5-fd733dc379a2,Jake Shimabukuro,"Shimabukuro, Jake",,https://www.setlist.fm/setlists/jake-shimabuku...
1,0330a83d-f61e-4989-adb3-afce3943c3ba,38 Special,38 Special,American rock band,https://www.setlist.fm/setlists/38-special-23d...
2,3ac482b8-1494-4071-a0e9-f192f9d2c2b0,Built to Spill,Built to Spill,,https://www.setlist.fm/setlists/built-to-spill...
3,511562a6-c381-44df-9bc4-27be779716b8,Tony! Toni! Toné!,Tony! Toni! Toné!,,https://www.setlist.fm/setlists/tony-toni-tone...
4,511562a6-c381-44df-9bc4-27be779716b8,Tony! Toni! Toné!,Tony! Toni! Toné!,,https://www.setlist.fm/setlists/tony-toni-tone...
5,d2b8465e-5020-4955-b21d-3ac24bbae7d3,Keilana,Keilana,Hawaiian/Filipino R&B/Soul musician from Honolulu,https://www.setlist.fm/setlists/keilana-7bfd66...
6,a408ec83-2ee0-4cf2-99d6-161fbe76dd16,Anuhea,Anuhea,Rylee Anuheake'alaokalokelani Jenkins,https://www.setlist.fm/setlists/anuhea-7bd05a8...
7,aaa436da-b331-4e58-a0fd-3d64d090c120,A Flock of Seagulls,"Flock of Seagulls, A",,https://www.setlist.fm/setlists/a-flock-of-sea...
8,25b75a66-ce83-4db3-b136-395a3c3784c4,The New Pornographers,"New Pornographers, The",,https://www.setlist.fm/setlists/the-new-pornog...
9,a616f35a-bbcc-42e4-9b50-0c95252eee2b,Super Diamond,Super Diamond,,https://www.setlist.fm/setlists/super-diamond-...
10,84803b1d-dcb3-490d-9af5-debbba64a011,Soccer Mommy,Soccer Mommy,,https://www.setlist.fm/setlists/soccer-mommy-4...
11,af8e4cc5-ef54-458d-a194-7b210acf638f,Cannibal Corpse,Cannibal Corpse,American Death Metal,https://www.setlist.fm/setlists/cannibal-corps...
12,c373c7f0-fddf-4c04-a327-19dd83590753,Immolation,Immolation,New York Death Metal,https://www.setlist.fm/setlists/immolation-13d...
13,b6b6f1cf-e1c8-46e9-bc54-1a63ed1f8d51,Wayne Newton,"Newton, Wayne",,https://www.setlist.fm/setlists/wayne-newton-5...
14,301b45a4-b8b9-410e-8344-4b4eaf96691a,Marshmello,Marshmello,,https://www.setlist.fm/setlists/marshmello-3c7...
15,b5415c6f-a2c3-48b4-a2a4-e9efbb577d10,Australian Bee Gees,Australian Bee Gees,,https://www.setlist.fm/setlists/australian-bee...
16,7bb60591-46f3-4147-b692-1814a87e832e,Barry Manilow,"Manilow, Barry",,https://www.setlist.fm/setlists/barry-manilow-...
17,4ae04ae2-4509-4a37-b486-1570a6dd17a4,Matt Pryor,"Pryor, Matt",,https://www.setlist.fm/setlists/matt-pryor-5bd...
18,7e8571b1-7c5a-4739-bc51-73d422ee9d74,Five Finger Death Punch,Five Finger Death Punch,,https://www.setlist.fm/setlists/five-finger-de...
19,4eca1aa0-c79f-481b-af8a-4a2d6c41aa5c,Miranda Lambert,"Lambert, Miranda",,https://www.setlist.fm/setlists/miranda-lamber...

In [51]:
g_artist_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mbid            20 non-null     object
 1   name            20 non-null     object
 2   sortName        20 non-null     object
 3   disambiguation  20 non-null     object
 4   url             20 non-null     object
dtypes: object(5)
memory usage: 928.0+ bytes

In [ ]:

ids = []
versionid = []
eventdate = []
lastupdated = []
artist = []
venue = []
song = []
for x in b_test['setlist']:
        song.append(y['name'])
        ids.append(x['id'])
        versionid.append(x['versionId'])
        eventdate.append(x['eventDate'])
        lastupdated.append(x['lastUpdated'])
        artist.append(x['artist']['name'])
        venue.append(x['venue']['name'])
b_setlist_test = pd.DataFrame({'id': ids, 'versionid': versionid, 'eventdate': eventdate, 'lastupdated': lastupdated, 'artist': artist, 'venue': venue, 'song': song})
b_setlist_test

In [19]:
header={
    "Accept":"application/json", 
    "x-api-key":api_key
}


i=requests.get("https://api.setlist.fm/rest/1.0/setlist/53d6f3ad", headers=header)
i_df=pd.DataFrame(i.json())
i_df.head()

,id,versionId,eventDate,lastUpdated,artist,venue,sets,info,url
mbid,53d6f3ad,g53c29b9d,30-01-1969,2021-12-14T08:26:08.000+0000,b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d,NaN,NaN,The Beatles' last public performance. Band pla...,https://www.setlist.fm/setlist/the-beatles/196...
name,53d6f3ad,g53c29b9d,30-01-1969,2021-12-14T08:26:08.000+0000,The Beatles,Apple Corps Rooftop,NaN,The Beatles' last public performance. Band pla...,https://www.setlist.fm/setlist/the-beatles/196...
sortName,53d6f3ad,g53c29b9d,30-01-1969,2021-12-14T08:26:08.000+0000,"Beatles, The",NaN,NaN,The Beatles' last public performance. Band pla...,https://www.setlist.fm/setlist/the-beatles/196...
disambiguation,53d6f3ad,g53c29b9d,30-01-1969,2021-12-14T08:26:08.000+0000,,NaN,NaN,The Beatles' last public performance. Band pla...,https://www.setlist.fm/setlist/the-beatles/196...
url,53d6f3ad,g53c29b9d,30-01-1969,2021-12-14T08:26:08.000+0000,https://www.setlist.fm/setlists/the-beatles-23...,https://www.setlist.fm/venue/apple-corps-rooft...,NaN,The Beatles' last public performance. Band pla...,https://www.setlist.fm/setlist/the-beatles/196...

In [ ]:
# rows: mbid, name, sortName, disambiguation, url, id, city, set
# columns: id, versionId, eventDate, lastUpdated, artist, venue, sets, info, url

In [21]:
# fifa_players.set_index('club')[['name', 'nationality']].transpose()

transposed_df =i_df.set_index('id')[['artist','venue']].transpose
transposed_df

<bound method DataFrame.transpose of                                                      artist  \
id
53d6f3ad               b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d
53d6f3ad                                        The Beatles
53d6f3ad                                       Beatles, The
53d6f3ad
53d6f3ad  https://www.setlist.fm/setlists/the-beatles-23...
53d6f3ad                                                NaN
53d6f3ad                                                NaN
53d6f3ad                                                NaN

                                                      venue
id
53d6f3ad                                                NaN
53d6f3ad                                Apple Corps Rooftop
53d6f3ad                                                NaN
53d6f3ad                                                NaN
53d6f3ad  https://www.setlist.fm/venue/apple-corps-rooft...
53d6f3ad                                           4bd627fe
53d6f3ad  {'id': '2643743', 'name': 'London', 'state': '...
53d6f3ad                                                NaN  >

In [23]:
t = i_df.set_index('id')[['artist']].transpose
t

<bound method DataFrame.transpose of                                                      artist
id
53d6f3ad               b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d
53d6f3ad                                        The Beatles
53d6f3ad                                       Beatles, The
53d6f3ad
53d6f3ad  https://www.setlist.fm/setlists/the-beatles-23...
53d6f3ad                                                NaN
53d6f3ad                                                NaN
53d6f3ad                                                NaN>

In [66]:
# another_fifa.pivot(index="name", columns="variable")

# i_df = i_df.pivot(index='artist', columns='venue')

TypeError: unhashable type: 'dict'

In [ ]:
m